<a href="https://colab.research.google.com/github/Lalith0024/Section_C_Group_11_Bank_Marketing_Dataset/blob/main/notebooks/02_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importing Required Libraries

In this step, we import essential Python libraries:
- pandas → for data manipulation and analysis
- numpy → for numerical operations

These libraries will be used throughout the data cleaning process.

In [69]:
import pandas as pd
import numpy as np

### Loading Raw Dataset

The dataset is loaded using pandas.

- The separator is set to `;` because the dataset is semicolon-separated.
- We check the shape to understand the size of the dataset.
- We display the first few rows to get an initial view of the data.

This helps us verify that the dataset is loaded correctly.

In [70]:
df = pd.read_csv('/content/raw_dataset.csv', sep=';')
print("Shape:", df.shape)
df.head()

Shape: (41188, 21)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

###  Basic Data Inspection

In this step, we explore the structure of the dataset:

- df.info() → shows column names, data types, and missing values
- df.describe() → provides statistical summary of numerical columns
- df.nunique() → shows the number of unique values in each column

This helps us understand data types, distributions, and potential issues.

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

In [72]:
df.describe()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
count,41188.00000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000
mean,40.02406,258.285010,2.567593,962.475454,0.172963,0.081886,93.575664,-40.502600,3.621291,5167.035911
std,10.42125,259.279249,2.770014,186.910907,0.494901,1.570960,0.578840,4.628198,1.734447,72.251528
min,17.00000,0.000000,1.000000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000
25%,32.00000,102.000000,1.000000,999.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000
50%,38.00000,180.000000,2.000000,999.000000,0.000000,1.100000,93.749000,-41.800000,4.857000,5191.000000
75%,47.00000,319.000000,3.000000,999.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000
max,98.00000,4918.000000,56.000000,999.000000,7.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000

In [73]:
df.nunique()

age                 78
job                 12
marital              4
education            8
default              3
housing              3
loan                 3
contact              2
month               10
day_of_week          5
duration          1544
campaign            42
pdays               27
previous             8
poutcome             3
emp.var.rate        10
cons.price.idx      26
cons.conf.idx       26
euribor3m          316
nr.employed         11
y                    2
dtype: int64

### Removing Duplicate Records

Duplicate rows can bias analysis and lead to incorrect insights.

- We remove duplicate entries using drop_duplicates()
- We verify the new dataset shape after removal

This ensures data integrity and avoids double counting.

In [74]:
df = df.drop_duplicates()
print("After removing duplicates:", df.shape)

After removing duplicates: (41176, 21)

### Fixing Data Types

The 'nr_employed' column is converted to integer type.

- This ensures consistency in numerical operations
- Prevents issues during analysis and visualization

Proper data types are important for accurate computations.

In [75]:
df['nr.employed'] = df['nr.employed'].astype(int)

### Renaming Columns for Better Clarity

Column names are standardized to improve readability and usability.

- Converted to descriptive and consistent naming format
- Replaced short or ambiguous names with meaningful ones

This makes the dataset easier to understand and work with.

In [76]:
df.columns = [
    "age",
    "job_type",
    "marital_status",
    "education_level",
    "credit_default",
    "has_housing_loan",
    "has_personal_loan",
    "contact_type",
    "contact_month",
    "contact_day",
    "call_duration_sec",
    "num_contacts_campaign",
    "days_since_last_contact",
    "num_previous_contacts",
    "previous_campaign_outcome",
    "employment_variation_rate",
    "consumer_price_index",
    "consumer_confidence_index",
    "interest_rate",
    "number_of_employees",
    "subscribed"
]

df.head()

,age,job_type,marital_status,education_level,credit_default,has_housing_loan,has_personal_loan,contact_type,contact_month,contact_day,...,num_contacts_campaign,days_since_last_contact,num_previous_contacts,previous_campaign_outcome,employment_variation_rate,consumer_price_index,consumer_confidence_index,interest_rate,number_of_employees,subscribed
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,no

### Standardizing Values

In this step:

- The target column is converted from 'yes/no' to 1/0 format
- 'unknown' values are standardized to 'Unknown' for consistency

This ensures uniform data representation across the dataset.

In [77]:
df["subscribed"] = df["subscribed"].map({"yes": 1, "no": 0})

df.replace("unknown", "Unknown", inplace=True)

df.head()

,age,job_type,marital_status,education_level,credit_default,has_housing_loan,has_personal_loan,contact_type,contact_month,contact_day,...,num_contacts_campaign,days_since_last_contact,num_previous_contacts,previous_campaign_outcome,employment_variation_rate,consumer_price_index,consumer_confidence_index,interest_rate,number_of_employees,subscribed
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,0
1,57,services,married,high.school,Unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,0
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,0
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,0
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,0

### Cleaning Education Levels

The 'illiterate' category is merged into 'basic.4y':

- Very few records exist for 'illiterate'
- Keeping it separate would create noise in analysis

This improves category consistency and reliability.

In [78]:
df["education_level"] = df["education_level"].replace("illiterate", "basic.4y")

### Converting Columns to Categorical Type

Categorical columns are explicitly converted to 'category' datatype:

- Improves memory efficiency
- Helps visualization tools (like Tableau) interpret data correctly

This step prepares the dataset for analysis and dashboarding.

In [79]:
categorical_cols = [
    "job_type", "marital_status", "education_level",
    "has_housing_loan", "has_personal_loan",
    "contact_type", "contact_month", "contact_day",
    "previous_campaign_outcome"
]

for col in categorical_cols:
    df[col] = df[col].astype("category")

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 41176 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        41176 non-null  int64
 1   job_type                   41176 non-null  category
 2   marital_status             41176 non-null  category
 3   education_level            41176 non-null  category
 4   credit_default             41176 non-null  object
 5   has_housing_loan           41176 non-null  category
 6   has_personal_loan          41176 non-null  category
 7   contact_type               41176 non-null  category
 8   contact_month              41176 non-null  category
 9   contact_day                41176 non-null  category
 10  call_duration_sec          41176 non-null  int64
 11  num_contacts_campaign      41176 non-null  int64
 12  days_since_last_contact    41176 non-null  int64
 13  num_previous_contacts      41176 non-null  int64
 14  previous_campaign_outcome  41176 non-null  category
 15  employment_variation_rate  41176 non-null  float64
 16  consumer_price_index       41176 non-null  float64
 17  consumer_confidence_index  41176 non-null  float64
 18  interest_rate              41176 non-null  float64
 19  number_of_employees        41176 non-null  int64
 20  subscribed                 41176 non-null  int64
dtypes: category(9), float64(4), int64(7), object(1)
memory usage: 4.4+ MB

### Handling Outliers in Campaign Calls

The 'num_contacts_campaign' column contains extreme values (very high number of calls).

- We cap the maximum value at 10 using `.clip()`
- This prevents outliers from distorting analysis and visualizations

This ensures more realistic and stable insights.

In [80]:
df["num_contacts_campaign"] = df["num_contacts_campaign"].clip(upper=10)

df["num_contacts_campaign"].describe()

count    41176.000000
mean         2.437075
std          2.030556
min          1.000000
25%          1.000000
50%          2.000000
75%          3.000000
max         10.000000
Name: num_contacts_campaign, dtype: float64

### Creating Age Groups

The 'age' column is grouped into meaningful categories:

- 0–25 → Young
- 26–35 → Early Career
- 36–50 → Mid Career
- 51–65 → Senior
- 65+ → Retired

Labels are assigned in numeric order (1–5) to ensure correct sorting in Tableau.

This simplifies analysis and improves visualization.

In [81]:
df["age_group"] = pd.cut(
    df["age"],
    bins=[0, 25, 35, 50, 65, 100],
    labels=[
        "1",
        "2",
        "3",
        "4",
        "5"
    ]
)

### 📞 Creating Call Intensity Feature

The number of campaign calls is grouped into buckets:

- 1 → First contact
- 2 → Second contact
- 3-5 → Moderate contact
- 6+ → High contact

This helps analyze how repeated calls affect customer conversion.

It is more interpretable than raw call counts.

In [82]:
df["call_intensity"] = df["num_contacts_campaign"].apply(
    lambda x: "1" if x == 1 else
              "2" if x == 2 else
              "4" if 3 <= x <= 5 else
              "6"
)

### Identifying Previously Contacted Customers

A new column 'contacted_before' is created:

- Yes → if the customer was contacted previously
- No → if no previous contact

This helps analyze whether prior interaction influences current success.

In [83]:
df["contacted_before"] = df["num_previous_contacts"].apply(
    lambda x: "Yes" if x > 0 else "No"
)
df[["num_previous_contacts", "contacted_before"]].head()

   num_previous_contacts contacted_before
0                      0               No
1                      0               No
2                      0               No
3                      0               No
4                      0               No

### Creating Contact Recency Feature

The 'days_since_last_contact' column is transformed into categories:

- 999 → Never Contacted
- ≤ 7 → Recently Contacted
- ≤ 30 → Moderately Contacted
- .> 30 → Long Ago Contacted

This converts a misleading numeric field into meaningful business categories.

It improves interpretability in analysis.

In [84]:
df["contact_recency"] = df["days_since_last_contact"].apply(
    lambda x: "Never Contacted" if x == 999 else
              "Recently Contacted" if x <= 7 else
              "Moderately Contacted" if x <= 30 else
              "Long Ago Contacted"
)

df[["days_since_last_contact", "contact_recency"]].head()

   days_since_last_contact  contact_recency
0                      999  Never Contacted
1                      999  Never Contacted
2                      999  Never Contacted
3                      999  Never Contacted
4                      999  Never Contacted

### Removing Raw Recency Column

The original 'days_since_last_contact' column is dropped:

- Contains placeholder value (999) which distorts analysis
- Already replaced by 'contact_recency'

This avoids duplication and misleading interpretations.

In [85]:
df.drop(columns=["days_since_last_contact"], inplace=True)

### Creating Final Target Variable

The 'subscribed' column is renamed to 'subscription_flag':

- Converted to binary format (1 = Yes, 0 = No)
- Old column is removed to avoid duplication

This becomes the main target variable for analysis.

In [86]:
df["subscription_flag"] = df["subscribed"]
df.drop(columns=["subscribed"], inplace=True)

### Creating Engineered Features

Additional features are created to simplify analysis:

- rate_environment → categorizes interest rates into Low, Medium, High
- prev_success_flag → indicates if previous campaign was successful

These features improve interpretability and support better insights.

In [87]:
# ADVANCED INSIGHT FEATURES

# 1. Rate Environment (simplifies economic conditions)
df['rate_environment'] = pd.cut(
    df['interest_rate'],
    bins=[0, 1.5, 3.5, 6],
    labels=['Low', 'Medium', 'High']
)

# w. Previous Success Flag (strongest predictor)
df['prev_success_flag'] = (df['previous_campaign_outcome'] == 'success').astype(int)

df[['rate_environment', 'prev_success_flag']].head()

  rate_environment  prev_success_flag
0             High                  0
1             High                  0
2             High                  0
3             High                  0
4             High                  0

### Creating Education Order for Sorting

An ordinal mapping is created for education levels:

- Assigns numerical values based on education hierarchy
- Ensures correct sorting in Tableau visualizations

This avoids incorrect alphabetical ordering.

In [88]:
#  EDUCATION ORDER FIX (for Tableau sorting)

edu_map = {
    'basic.4y':1,
    'basic.6y':2,
    'basic.9y':3,
    'high.school':4,
    'professional.course':5,
    'university.degree':6,
    'Unknown':0
}

df['education_ordinal'] = df['education_level'].map(edu_map)

### Final Dataset Verification

Final checks are performed:

- Confirm dataset shape
- Display sample rows

This ensures all cleaning steps were applied correctly.

In [89]:
print(df.shape)
df.head()

(41176, 27)

,age,job_type,marital_status,education_level,credit_default,has_housing_loan,has_personal_loan,contact_type,contact_month,contact_day,...,interest_rate,number_of_employees,age_group,call_intensity,contacted_before,contact_recency,subscription_flag,rate_environment,prev_success_flag,education_ordinal
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,4.857,5191,4,1,No,Never Contacted,0,High,0,1
1,57,services,married,high.school,Unknown,no,no,telephone,may,mon,...,4.857,5191,4,1,No,Never Contacted,0,High,0,4
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,4.857,5191,3,1,No,Never Contacted,0,High,0,4
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,4.857,5191,3,1,No,Never Contacted,0,High,0,2
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,4.857,5191,4,1,No,Never Contacted,0,High,0,4

### Exporting Cleaned Dataset

The cleaned dataset is saved as a CSV file:

- Ready for EDA and dashboard creation
- Ensures reproducibility of results

This marks the completion of the data cleaning process.

In [90]:
df.to_csv("cleaned_bank_data.csv", index=False)
print("✅ FINAL CLEANED DATASET READY")

✅ FINAL CLEANED DATASET READY